# 创建NumPy数组`np.array(list)`

In [15]:
import numpy as np

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

#嵌套序列（如等长列表的列表）将被转换为多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# NumPy数组的维度`.ndim`和形状`.shape`

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

# NumPy数组的数据类型`.dtype`

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int64')

# 使用其它函数创建NumPy数组

## 创建具有给定长度或形状的 0或1 数组`np.zero(int/tuple)`、`np.ones(int/tuple)`

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 创建一个数组，但不将其值初始化为任何特定值`np.empty(int/tuple)`。创建更高维度的数组，可以传递一个表示形状的元组。
此函数返回未初始化的内存，因此可能包含非零的 “垃圾” 值。仅当打算用数据填充新数组时，才应使用此函数

In [29]:
np.empty((2, 3, 2))

array([[[1.47460527e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [8.01057146e-307, 6.82116729e-043]],

       [[5.24869935e-090, 2.12677493e+160],
        [5.45022610e-067, 1.48609835e-076],
        [3.99910963e+252, 7.91843413e+165]]])

# 类似Python内置函数range()的一个数组值版本`np.arange()`

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 标准数组创建函数的简短列表如下,由于 NumPy 专注于数值计算，因此数据类型（如果未指定）在许多情况下将是（浮点）。


| 功能 | 描述 |
|-------|-------|
| array | 将输入数据（列表、元组、数组或其他序列类型）通过推断数据类型或显式指定数据类型转换为ndarray；默认情况下会复制输入数据 |
| asarray | 将输入转换为ndarray，但如果输入已经是ndarray，则不进行复制 |
| arange | 类似于内置函数，但返回的是一个ndarray而不是列表range |
| ones,<br>ones_like | 根据给定的形状和数据类型生成一个全为1的数组；接收另一个数组，并生成一个具有相同形状和数据类型的新数组。 |
| zeros,<br>zeros_like | 根据给定的形状和数据类型生成一个全为0的数组；接收另一个数组，并生成一个具有相同形状和数据类型的新数组 |
| empty,<br>empty_like | 通过分配新的内存来创建新数组，但不要像ones或zeros那样用任何值填充它们 |
| full,<br>full_like | 根据给定的形状和数据类型生成一个数组，并将所有值设置为指定的“填充值”；<br>接受另一个数组，并生成一个具有相同形状和数据类型且已填充的数组（full_like） |
| eye, identity | 创建一个N × N的单位矩阵（对角线上为1，其他位置为0） |

In [79]:
# 使用np.arange创建一个等差数列
np.arange(0, 10, 2)  # 从0开始，到10结束（不包括10），步长为2

array([0, 2, 4, 6, 8])

In [80]:
# 使用np.linspace创建一个等间距数组
np.linspace(0, 1, 5)  # 从0到1，包含5个等间距的数

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
arr3=np.asarray(data1)

In [36]:
arr3

array([6. , 7.5, 8. , 0. , 1. ])

In [37]:
np.ones_like(arr3)

array([1., 1., 1., 1., 1.])

In [38]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [70]:
np.empty((6,6))

array([[6.95192624e-310, 1.63041663e-322, 1.47460352e-311,
        1.47463093e-311, 1.47457430e-311, 1.47461066e-311],
       [1.47461909e-311, 2.12199579e-314, 2.96439388e-323,
        2.12199579e-314, 4.88059033e-313, 2.58883486e-312],
       [2.12199583e-314, 8.39911598e-323, 8.89318163e-323,
        8.39911598e-323, 8.89318163e-323, 6.95192624e-310],
       [1.47461821e-311, 1.47463604e-311, 1.47461613e-311,
        1.47463602e-311, 1.47463611e-311, 1.47460845e-311],
       [1.47460845e-311, 1.47462856e-311, 1.47462954e-311,
        1.47457465e-311, 1.47462963e-311, 6.95192624e-310],
       [1.47457399e-311, 1.47463604e-311, 1.47457400e-311,
        1.47457400e-311, 1.47464118e-311, 1.47457672e-311]])

In [74]:
np.empty_like(arr3)

array([  25895968444448860,   23925768161198147,   32370111954616435,
                         0, 2338621054691311616])

In [75]:
np.full((3,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [76]:
np.full_like(arr3,7)

array([7, 7, 7, 7, 7])

In [77]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [78]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])