# 直接指定ndarray数据类型np.array(list, `dtype=np.float64`)

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 2, 3], dtype=np.int32)

In [3]:
arr1.dtype

dtype('float64')

In [4]:
arr2.dtype

dtype('int32')

# NumPy支持的数据类型的完整列表如下

| 类型 | 类型代码 | 描述 |
|-------|-------|-------|
| int8, uint8 | i1, u1 | 有符号和无符号的8位（1字节）整数类型 |
| int16, uint16 | i2, u2 | 有符号和无符号的16位整数类型 |
| int32, uint32 | i4, u4 | 有符号和无符号的32位整数类型 |
| int64, uint64 | i8, u8 | 有符号和无符号的64位整数类型 |
| float16 | f2 | 半精度浮点数 |
| float32 | f4 or f | 标准单精度浮点；与C语言中的float类型兼容 |
| float64 | f8 or d | 标准双精度浮点；与C语言的double类型和Python的对象浮点类型兼容 |
| float128 | f16 or g | 扩展精度浮点数 |
| complex64,<br> complex128,<br> complex256 | c8, c16, c32 | 分别由两个32位、64位或128位浮点数表示的复数 |
| bool | ? | 布尔类型存储及值：True False |
| object | O | Python 对象类型；值可以是任何 Python 对象 |
| ~~string_~~<br>str_ | S | 定长ASCII字符串类型（每个字符1字节）；例如，要创建一个长度为10的字符串数据类型，使用'S10' |
| unicode_ | U | 定长Unicode类型（字节数平台特定）；与（例如，string_'U10'）具有相同的规范语义 |

有符号整数可以表示正整数和负整数，而无符号整数只能表示非零整数。例如，（有符号 8 位整数）可以表示从 -128 到 127（含）的整数，而（无符号 8 位整数）可以表示 0 到 255。

In [63]:
np.array([0, 1, 2, 3, 0, 9, 0], dtype=np.bool)

array([False,  True,  True,  True, False,  True, False])

In [64]:
np.array([0, 1, 2, 3, 0, 9, 0], dtype='?')

array([False,  True,  True,  True, False,  True, False])

In [68]:
np.array([0, 1, 2, 3, 0, 9, 0], dtype='S1')

array([b'0', b'1', b'2', b'3', b'0', b'9', b'0'], dtype='|S1')

In [78]:
np.array(['123', '456'], dtype='S1')    #固定长度的 ASCII 字符串类型，使用该类型时要小心，因为 NumPy 中的字符串数据是固定大小的，并且可能会在没有警告的情况下截断输入

array([b'1', b'4'], dtype='|S1')

In [79]:
np.array([0, 12, 2, 3, 0, 9, 0], dtype='U1')

array(['0', '1', '2', '3', '0', '9', '0'], dtype='<U1')

In [80]:
np.array(['你好', '世界'] , dtype='U1')    #固定长度的 Unicode 类型，使用该类型时要小心，因为 NumPy 中的字符串数据是固定大小的，并且可能会在没有警告的情况下截断输入

array(['你', '世'], dtype='<U1')

In [81]:
np.array([0, 1, 2, 3, 0, 9, 0], dtype='O')

array([0, 1, 2, 3, 0, 9, 0], dtype=object)

In [82]:
np.array([0, 123, 4567, 6, 0, 9, 0], dtype='S1')

array([b'0', b'1', b'4', b'6', b'0', b'9', b'0'], dtype='|S1')

# 将数组的数据转换为其它数据类型 `数组.astype(np.float64)`
即使新的数据类型与旧的数据类型相同，调用.astype（）（函数或方法）总是会创建一个新的数组（数据的副本）
## 整数被强制转换为浮点数

In [5]:
arr = np.array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int64')

In [8]:
float_arr = arr.astype(np.float64)

In [9]:
float_arr

array([1., 2., 3., 4., 5.])

In [10]:
float_arr.dtype

dtype('float64')

## 浮点数强制转换为整数数据类型，则小数部分将被截断

In [11]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [12]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [13]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

## 表示数字的字符串数组，可以转换为数字形式

In [39]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.str_)    #np.string_ 已经被弃用，建议使用 np.str_ 或者 Python 3 中的 str 类型

In [43]:
# numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=str) 

In [44]:
# numeric_strings = np.array(["1.25", "-9.6", "42"], dtype='S10')

In [45]:
numeric_strings

array(['1.25', '-9.6', '42'], dtype='<U4')

In [46]:
numeric_strings.astype(float)    #用float代替了np.float64；NumPy将Python类型别名为其自己的等效数据类型。

array([ 1.25, -9.6 , 42.  ])

In [47]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

## 也可以使用另一个数组的属性`.dtype`

In [48]:
int_array = np.arange(10)

In [49]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [50]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 使用类型代码，有速记类型的代码字符串，也可以用它来引用

In [51]:
zeros_uint32 = np.zeros(8, dtype="u4")

In [52]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)