# 大小相同的数组之间的任何算术运算，都是按元素逐一进行操作的。

In [1]:
import numpy as np

arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [2]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
arr *  arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [4]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [6]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

# 与标量进行的算术运算会将标量参数传播到数组中的每个元素

In [7]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

# 相同大小数组之间的比较会产生布尔数组

In [9]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [10]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [12]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

# 对不同大小的数组之间进行的运算进行评估称为广播（broadcasting）