# NumPy一维数组的索引切片操作类似于Python列表

In [1]:
import numpy as np

arr = np.arange(10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5]

np.int64(5)

In [4]:
arr[5:8]

array([5, 6, 7])

In [5]:
# arr[5:8]=np.arange(3)

In [6]:
# arr

## 如果为切片分配标量值，则该值将传播（或从此广播）到整个选择
NumPy数组与 Python 的内置列表的一个重要区别是数组切片是原始数组上的视图。这意味着数据不会被复制，对视图的任何修改都将反映在源数组中

In [7]:
arr[5:8] = 12

In [8]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
arr_slice = arr[5:8]

In [10]:
arr_slice

array([12, 12, 12])

In [11]:
arr_slice[1] = 12345

In [12]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [13]:
arr_slice[:] = 64

In [14]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [15]:
a=arr_slice

In [16]:
arr_slice

array([64, 64, 64])

In [17]:
a=1

In [18]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

# 想要得到 ndarray 切片的副本而不是视图，则需要显式复制数组。`数组切片.copy()`

In [19]:
arr[5:8].copy()

array([64, 64, 64])

# 在二维数组上索引，每个索引处的元素不再是标量，而是一维数组。
在二维数组上进行索引，可以将轴0视为数组的“行”，轴1视为数组的“列”
![二维数组索引说明](pda3_0401.png)

In [20]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [21]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2d[2]

array([7, 8, 9])

## 通过传递一个逗号分隔的索引列表来选择更低维度的元素。下面两个是等效的。
NumPy数组的这种多维索引语法不适用于常规 Python列表。

In [23]:
arr2d[0][2]

np.int64(3)

In [24]:
arr2d[0, 2]

np.int64(3)

# 在多维数组中，如果省略后面的索引，返回的对象将是一个低维 ndarray，由沿较高维度的所有数据组成。

In [25]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [26]:
arr3d    #2 × 2 × 3 数组

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[0]    #2 × 3 数组

array([[1, 2, 3],
       [4, 5, 6]])

## 既可以赋值标量值，也可以赋值数组(注意数组的的维度和形状应该与切片产生的数组一样)。

In [28]:
old_values = arr3d[0].copy()

In [29]:
arr3d[0] = 42

In [30]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
arr3d[0] = old_values

In [32]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
# arr3d[0] = np.full((2,3),0)

In [34]:
# arr3d

In [35]:
# arr3d[0] = np.zeros((2,3))

In [36]:
# arr3d

## 通过索引列表获得一个一维数组
注意返回的数组都是视图

In [37]:
arr3d[1, 0]

array([7, 8, 9])

In [43]:
x = arr3d[1]    #上面通过索引列表与这里分两步进行索引是相同的

In [44]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [45]:
x[0]

array([7, 8, 9])

# NumPy一维数组切片语法与Python一维列表切片语法一样。

In [46]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [47]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

# 对于NumPy二维数组进行切片有点不同。
切片操作是沿着某个轴选择一系列元素

In [48]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

## 可以传递多个切片
像这样切片时，总是获得相同维数的数组视图

In [56]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

# 混合整数索引和切片，可以获得低维切片

In [57]:
lower_dim_slice = arr2d[1, :2]

In [58]:
lower_dim_slice.shape    #虽然（前者）是二维的，但（后者）是一维的，并且它的形状是一个具有一个轴大小的元组

(2,)

In [61]:
lower_dim_slice

array([4, 5])

In [62]:
arr2d[:2, 2]

array([3, 6])

## 冒号本身的意思是取整个轴

In [63]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

# 对切片表达式进行赋值实际上是对整个所选范围进行赋值

In [64]:
arr2d[:2, 1:] = 0

In [65]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# 二维数组切片
![二维数组切片](pda3_0402.png)