# 假设每个名称对应于data数组中的一行，并且我们希望选择具有相应名称的所有行。就像算术运算一样，对数组进行比较也是向量化的。因此，与字符串进行比较会产生一个布尔数组
通过布尔索引从数组中选择数据并将结果分配给一个新变量时，总是会创建数据的副本，即使返回的数组未发生变化。

In [1]:
import numpy as np

names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [2]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [3]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [4]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

## 在为数组编制索引时，可以传递此 Boolean 数组

In [5]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

## 布尔数组的长度必须与它正在索引的数组轴的长度相同。可以将布尔数组与切片或整数混合匹配

In [6]:
data[names == "Bob", 1:]    #行中进行选择，同时也对列进行索引

array([[7],
       [0]])

In [7]:
data[names == "Bob", 1]

array([7, 0])

# 其它索引条件，使用条件运算符`!=`或者对条件取反`~`

In [8]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [9]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [10]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [11]:
cond = names == "Bob"    #与上面的一样，通过~反转变量引用的布尔数组

In [12]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

# 组合多个布尔条件，可以使用布尔算术运算符，如（和`&`）和（或`|`）
Python关键字`and`和`or`不适用于布尔数组算数运算符。

In [13]:
mask = (names == "Bob") | (names == "Will")

In [14]:
mask

array([ True, False,  True,  True,  True, False, False])

# 对满足条件的元素进行重新赋值

In [15]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [16]:
data < 0

array([[False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True,  True],
       [False, False]])

In [17]:
data[data < 0]

array([ -5, -12,  -4])

In [18]:
data[data < 0] = 0

In [19]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

# 用一维布尔数组给整行或整列重新赋值

In [20]:
names != "Joe"

array([ True, False,  True,  True,  True, False, False])

In [21]:
data[names != "Joe"] = 7

In [22]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])