# 花式索引（Fancy indexing）是NumPy采用的一个术语，用于描述使用整数数组进行索引。

In [3]:
import numpy as np

arr = np.zeros((8, 4))

for i in range(8):
    arr[i] = i

In [4]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

## 按照特定顺序选择行的子集，只需传递一个包含指定顺序的整数的列表或ndarray即可。

In [8]:
arr[[4, 3, 0, 6]]    

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

## 使用负索引可以从末尾选择行

In [7]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

## 传递多个索引数组时的操作略有不同，它会为每个索引元组选择一个对应的一维元素数组

In [9]:
arr = np.arange(32).reshape((8, 4))

In [10]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [12]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]    #在这里，选择了元素(1, 0)，(5, 3)，(7, 1)和(2, 2)。当使用与轴数量一样多的整数数组进行花式索引时，结果总是一维的

array([ 4, 23, 29, 10])

## 通过选择矩阵行和列（排列顺序）的一个子集来形成一个矩形区域

In [13]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [14]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [ ]:
# 