# 转置（Transposing）是一种特殊的重塑形式，会返回一个对底层数据的视图，而不会复制任何内容。数组通过特殊属性`数组.T`或`数组.transpose()`方法进行转置。

In [1]:
import numpy as np

arr = np.arange(15).reshape((3, 5))

In [29]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [30]:
arr.T

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [31]:
arr.transpose()

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

## 数组转置应用场景，计算内矩阵积`np.dot()`

In [5]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])

In [6]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [8]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

## 矩阵乘法的另一种方式`@`

In [9]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

# 简单的转置是交换轴的一个特例。ndarray还有一个交换数组两个轴的方法，它接受一对轴编号，并交换指定的轴以重新排列数据。`数组.swapaxes(0, 1)`
swapaxes 同样会返回一个数据的视图，而不会进行复制

In [21]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [27]:
arr.swapaxes(0, 1)    #使用 swapaxes(0, 1) 方法交换了数组的轴 0（行）和轴 1（列）

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])