# `np.random.standard_normal(size=(tuple))`可以用来补充内置的Python random模块，可以从正态分布中高效地生成整个样本值数组。

In [1]:
import numpy as np

samples = np.random.standard_normal(size=(4, 4))

In [2]:
samples

array([[-1.46924658,  0.51095374,  0.01761964,  2.2163895 ],
       [-0.87927577,  1.37182992, -1.44009813, -1.72405217],
       [-1.98437248,  1.7256857 ,  0.75319363, -0.2907127 ],
       [ 0.66348594,  0.7411612 ,  0.19078624,  0.40545398]])

## `np.random.standard_normal()`与python`random.normalvariate()`函数生成指定数量的标准正态分布随机数做速度比较。


In [3]:
from random import normalvariate

N = 1_000_000

In [4]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

1.95 s ± 214 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit np.random.standard_normal(N)

42.7 ms ± 1.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 这些随机数并非真正随机（而是伪随机），而是由一个可配置的随机数生成器生成的，该生成器以确定性方式决定生成哪些值。函数会使用该模块的默认随机数生成器，也可以配置为使用特定的生成器。<br>`rng = np.random.default_rng(seed=12345)`

In [6]:
rng = np.random.default_rng(seed=12345)

In [7]:
data = rng.standard_normal((2, 3))

In [8]:
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [9]:
type(rng)

numpy.random._generator.Generator

# NumPy随机数生成器部分方法列表如下

| 方法 | 描述 |
|-------|-------|
| permutation | 返回一个序列的随机排列，或者返回一个排列后的范围 |
| shuffle | 原地随机排列一个序列 |
| uniform | 从均匀分布中抽取样本 |
| integers | 从给定的低到高范围内随机抽取整数 |
| standard_normal | 从均值为0、标准差为1的正态分布中抽取样本 |
| binomial | 从二项分布中抽取样本 |
| normal | 从正态分布（高斯分布）中抽取样本 |
| beta | 从贝塔分布中抽取样本 |
| chisquare | 从卡方分布中抽取样本 |
| gamma | 从伽马分布中抽取样本 |
| uniform | 从均匀[0, 1)分布中抽取样本 |

In [10]:
rng.uniform(size=(5,5))

array([[0.59830875, 0.18673419, 0.67275604, 0.94180287, 0.24824571],
       [0.94888115, 0.66723745, 0.09589794, 0.44183967, 0.88647992],
       [0.6974535 , 0.32647286, 0.73392816, 0.22013496, 0.08159457],
       [0.1598956 , 0.34010018, 0.46519315, 0.26642103, 0.8157764 ],
       [0.19329439, 0.12946908, 0.09166475, 0.59856801, 0.8547419 ]])

In [11]:
rng.normal(size=(4,4))

array([[ 0.8286332 , -0.95898831, -1.20938829, -1.41229201],
       [ 0.54154683,  0.7519394 , -0.65876032, -1.22867499],
       [ 0.25755777,  0.31290292, -0.13081169,  1.26998312],
       [-0.09296246, -0.06615089, -1.10821447,  0.13595685]])

In [12]:
a = rng.integers(1,10,size=(4,5))

In [13]:
a

array([[8, 4, 1, 1, 1],
       [6, 4, 3, 6, 1],
       [5, 6, 1, 2, 4],
       [3, 9, 4, 6, 2]])

In [15]:
rng.shuffle(a)

In [16]:
a

array([[8, 4, 1, 1, 1],
       [5, 6, 1, 2, 4],
       [3, 9, 4, 6, 2],
       [6, 4, 3, 6, 1]])