# 通用函数 （ufunc） 是对 ndarray 中的数据执行元素运算的函数，函数接收一个或多个标量值，并生成一个或多个标量值的结果。

In [1]:
import numpy as np

arr = np.arange(10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 一元ufuncs    `np.sqrt(数组)、np.exp(数组)......`
一元ufuncs是指那些只接受一个数组作为输入，并返回另一个数组作为输出的ufuncs。

In [3]:
np.sqrt(arr)    # 计算数组 arr 中每个元素的平方根

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)    # 对数组中的每个元素进行指数运算

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

# 二元ufuncs    `np.maximum(数组1, 数组2)......`
二元ufuncs是指那些接受两个数组作为输入，并返回一个数组作为输出的ufuncs。

In [5]:
rng = np.random.default_rng(seed=12345)

In [6]:
x = rng.standard_normal(8)

In [7]:
y = rng.standard_normal(8)

In [8]:
x

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ])

In [9]:
y

array([ 0.36105811, -1.95286306,  2.34740965,  0.96849691, -0.75938718,
        0.90219827, -0.46695317, -0.06068952])

In [10]:
np.maximum(x, y)    # np.maximum计算了x和y中元素级别最大的元素

array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

# 虽然不常见，一个通用函数（ufunc）可以返回多个数组。`numpy.modf(数组)`就是一个例子：它是Python内置函数`modf`的向量化版本，它返回一个浮点数组的分数部分和整数部分。

In [11]:
arr = rng.standard_normal(7) * 5

In [12]:
arr

array([ 3.94422172, -6.28334067,  2.87928757,  6.99489497,  6.6114903 ,
       -1.49849258,  4.51459671])

In [13]:
remainder, whole_part = np.modf(arr)

In [14]:
np.modf(arr)

(array([ 0.94422172, -0.28334067,  0.87928757,  0.99489497,  0.6114903 ,
        -0.49849258,  0.51459671]),
 array([ 3., -6.,  2.,  6.,  6., -1.,  4.]))

In [15]:
remainder

array([ 0.94422172, -0.28334067,  0.87928757,  0.99489497,  0.6114903 ,
       -0.49849258,  0.51459671])

In [16]:
whole_part

array([ 3., -6.,  2.,  6.,  6., -1.,  4.])

# 通用函数（ufunc）接受一个可选参数，该参数允许它们将结果赋值到现有数组中，而不是创建一个新数组。

In [17]:
arr

array([ 3.94422172, -6.28334067,  2.87928757,  6.99489497,  6.6114903 ,
       -1.49849258,  4.51459671])

In [18]:
out = np.zeros_like(arr)

In [19]:
out

array([0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.add(arr, 1)

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [21]:
np.add(arr, 1, out=out)

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [22]:
out

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

# 列出了一些NumPy的一元ufunc和二元ufunc如下

# 一些一元通用函数

| 功能 | 描述 |
|-------|-------|
| abs, fabs | 逐元素地计算整数、浮点数或复数的绝对值 |
| sqrt | 计算各元素的平方根，等价于arr**0.5 |
| square | 计算各元素的平方，等价于arr **2 |
| exp | 计算各元素的自然指数$e^x$ |
| log, log10, log2, log1p | 分别为自然对数(底数为e)、底数为10的对数、底数为2的对数和 log(1+x) |
| sign | 计算各元素的符号:1(正数)、0(零)、-1(负数) |
| ceil | 计算各元素的最大整数值，即大于等于该值的最小整数 |
| floor | 计算各元素的最小整数值，即小于等于该值的最大整数 |
| rint | 将各元素值四舍五入到最接近的整数，保留 dtype |
| modf | 将数组的小数部分和整数部分以两个独立数组的形式返回 |
| isnan | 返回表示“哪些值是 NaN(不是一个数值)”的布尔型数组 |
| isfinite, isinf | 分别返回表示“哪些元素是有限的(非inf，非 NaN)”和“哪些元素是无限的”的布尔型数组 |
| cos, cosh, sin, sinh, tan, tanh | 正则三角函数和双曲三角函数 |
| arccos, arccosh, arcsin, arcsinh, arctan, arctanh | 反三角函数 |
| logical_not | 对数组的元素按位取反，等价于~arr |


# 一些二元通用函数

| 功能 | 描述 |
|-------|-------|
| add | 在数组中添加相应的元素 |
| subtract | 从第一个数组的元素中减去第二个数组的元素 |
| multiply | 将数组中对应的元素相乘 |
| divide, floor_divide | 除或整除(截断余数) |
| power | 第一个数组中的各元素以第二个数组中的相应元素做幂次方 |
| maximum, fmax | 逐个元素计算最大值，fmax忽略NaN |
| minimum, fmin | 逐个元素计算最小值，fmin 忽略NaN |
| mod | 元素级的求模计算(除法的余数) |
| copysign | 将第二个数组中元素值的符号复制给第一个数组中的元素 |
| greater, greater_equal, less, <br>less_equal, equal, not_equal | 执行元素级的比较运算，返回布尔型数组。<br>相当于中缀运算符 >、>=、<、<=、==、!= |
| logical_and | 执行元素级的逻辑与(&)运算 |
| logical_or | 执行元素级的逻辑或($|$)运算 |
| logical_xor | 执行元素级的逻辑异或(^)运算 |


In [23]:
rng = np.random.default_rng(seed=12345)

arr1 = rng.integers(1,10,size=(4,5))

arr2 = rng.integers(1,10,size=(4,5))

In [24]:
arr1

array([[7, 3, 8, 3, 2],
       [8, 6, 7, 9, 4],
       [8, 3, 6, 6, 2],
       [2, 3, 7, 6, 9]])

In [25]:
arr2

array([[7, 3, 9, 9, 7],
       [7, 2, 1, 3, 4],
       [1, 8, 5, 7, 2],
       [3, 2, 7, 7, 2]])

In [26]:
np.square(arr1)

array([[49,  9, 64,  9,  4],
       [64, 36, 49, 81, 16],
       [64,  9, 36, 36,  4],
       [ 4,  9, 49, 36, 81]])

In [27]:
np.add(arr1,arr2)

array([[14,  6, 17, 12,  9],
       [15,  8,  8, 12,  8],
       [ 9, 11, 11, 13,  4],
       [ 5,  5, 14, 13, 11]])

In [28]:
np.maximum(arr1,arr2)

array([[7, 3, 9, 9, 7],
       [8, 6, 7, 9, 4],
       [8, 8, 6, 7, 2],
       [3, 3, 7, 7, 9]])

In [29]:
np.greater(arr1, arr2)

array([[False, False, False, False, False],
       [ True,  True,  True,  True, False],
       [ True, False,  True, False, False],
       [False,  True, False, False,  True]])