# 线性代数（如矩阵乘法、矩阵分解、行列式以及其他方阵数学等）是许多数组库的重要组成部分。

## 矩阵乘法  `数组1.dot(数组2)`等价于`np.dot(数组1, 数组2)`

In [1]:
import numpy as np
rng = np.random.default_rng(seed=12345)

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [3]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [5]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [6]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [15]:
x @ y

array([[ 28.,  64.],
       [ 67., 181.]])

In [7]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [8]:
np.dot(y, x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

## 一个二维数组跟一个大小合适的一维数组的矩阵点积运算将会得到一个一维数组。

In [9]:
x @ np.ones(3)

array([ 6., 15.])

## numpy.linalg中有一组标准的矩阵分解运算以及求逆和求行列式等方法。

In [10]:
from numpy.linalg import inv, qr

In [11]:
X = rng.standard_normal((5, 5))

In [12]:
mat = X.T @ X

In [13]:
inv(mat)

array([[ 0.15548538, -0.36723081, -0.52638547, -0.2300642 , -0.04646089],
       [-0.36723081,  2.54917814,  3.47827334,  1.48196722,  0.22206454],
       [-0.52638547,  3.47827334,  5.46389554,  2.46214396,  0.63467543],
       [-0.2300642 ,  1.48196722,  2.46214396,  1.38302896,  0.33430132],
       [-0.04646089,  0.22206454,  0.63467543,  0.33430132,  0.33879566]])

In [14]:
mat @ inv(mat)

array([[ 1.00000000e+00,  4.99285027e-17, -2.32472626e-16,
        -2.35388056e-16, -1.12575057e-18],
       [ 1.55867966e-16,  1.00000000e+00,  9.98311990e-17,
        -1.96348091e-16, -3.86511231e-16],
       [-6.92418622e-17, -7.91606813e-16,  1.00000000e+00,
         5.64803789e-16,  1.61057761e-16],
       [-2.37101845e-16,  1.84817406e-15,  3.81257497e-15,
         1.00000000e+00,  3.71349003e-16],
       [ 9.72642079e-17,  2.31009855e-16, -7.19939179e-17,
        -4.80724193e-16,  1.00000000e+00]])

# 常用的线性代数函数如下表

| 函数 | 说明 |
|-------|-------|
| diag | 以一维数组的形式返回方阵的对角线(或非对角线)元素，或将一维数组转换为方阵(非对角线元素为0) |
| top | 矩阵乘法 |
| trace | 计算对角线元素的和 |
| det | 计算矩阵行列式 |
| eig | 计算方阵的特征值和特征向量 |
| inv | 计算方阵的逆矩阵 |
| pinv | 计算矩阵的 Moore-Penrose 伪逆 |
| qr | 计算 QR 分解 |
| svd | 计算奇异值分解(SVD) |
| solve | 求解 x 的线性系统 Ax = b，其中 A 是方阵 |
| lstsq | 计算最小二乘解Ax = b |

